be/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import PostSiteMap

sitemaps = {
    "posts": PostSiteMap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('cms.urls', namespace='cms')),
    path(
        'sitemap.xml',
        sitemap,
        {
            "sitemaps": sitemaps,
        },
        name="django.contrib.sitemaps.views.sitemap"
    )
]

be/blog/cms/urls.py
from django.urls import path
from .views import (
    post_list,
    post_detail,
    PostListView,
    post_share,
    post_comment,
    post_search,
)
from .feeds import LatestPostsFeed

app_name = 'cms'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('<int:post_id>/comment/', post_comment, name="post_comment"),
    path('feed/', LatestPostsFeed(), name="post_feed"),
    path('search/', post_search, name="post_search"),
]

be/blog/cms/models/comment.py
from django.db import models
from cms.models import Post


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(
                fields=['created']
            ),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

be/blog/cms/models/post.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='cms_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Our Custom manager

    class Meta:
        ordering = ['-publish']  # From newest to oldest
        indexes = [
            models.Index(fields=['-publish'])
            # Hyphen before the field name to define the index in descending order (Not supported in MySQL)
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'cms:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

be/blog/cms/models/post_model.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post:
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='cms_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )

    class Meta:
        ordering = ['-publish']  # From newest to oldest
        indexes = [
            models.Index(fields=['-publish'])
            # Hyphen before the field name to define the index in descending order (Not supported in MySQL)
        ]

    def __str__(self):
        return self.title

be/blog/cms/forms/comment_form.py
from cms.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

be/blog/cms/forms/email_post_form.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

be/blog/cms/forms/search_form.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

be/blog/cms/views/post_comment_view.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from cms.models import Post, Comment
from cms.forms import CommentForm


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "cms/post/comment.html",
        {
            "post": post,
            "form": form,
            "comment": comment
        }
    )

be/blog/cms/views/post_detail_view.py
from django.http import Http404
from cms.models import Post, Comment
from django.shortcuts import render, get_object_or_404
from cms.forms import CommentForm
from django.db.models import Count


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]
    return render(
        request,
        'cms/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )

be/blog/cms/views/post_list_view.py
from django.shortcuts import render, get_object_or_404
from cms.models import Post
from django.core.paginator import (
    Paginator,
    EmptyPage,
    PageNotAnInteger
)
from django.views.generic import ListView
from taggit.models import Tag


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'cms/post/list.html',
        {
            'posts': posts,
            'tag': tag,
        }
    )


class PostListView(ListView):
    """Alternative post list view"""
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "cms/post/list.html"

be/blog/cms/views/post_search_view.py
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank
)
from cms.forms import SearchForm
from cms.models import Post
from django.shortcuts import render


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_vector = SearchVector('title', 'body', config='spanish')
            search_query = SearchQuery(query)
            # search_query = SearchQuery(query, config='spanish')
            search_rank = SearchRank(search_vector, search_query)
            # results = Post.published.annotate(
            #     search=search_vector,
            #     rank=search_rank,
            # ).filter(search=search_query).order_by('-rank')
            results = Post.published.annotate(
                search=search_vector,
                rank=search_rank,
            ).filter(search=search_query).order_by('-rank')
    return render(
        request,
        'cms/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

be/blog/cms/views/post_share_view.py
from cms.forms import EmailPostForm
from django.shortcuts import get_object_or_404, render
from cms.models import Post
from django.core.mail import send_mail


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if not form.is_valid():
            form = EmailPostForm()
        else:
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(
                subject,
                message,
                'test@example.com',
                [cd['to']]
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        "cms/post/share.html",
        {
            "post": post,
            "form": form,
            'sent': sent,
        }
    )

be/blog/templates/cms/post/comment.html
{% extends "cms/base.html" %}

{% block title %}
    Add a comment
{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "cms/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

be/blog/templates/cms/post/detail.html
{% extends "cms/base.html" %}
{% load cms_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
    <a href="{% url "cms:post_share" post.id %}">
    Share this post
    </a>
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments.</p>
{% endfor %}
{% include "cms/post/includes/comment_form.html" %}
{% endblock %}

be/blog/templates/cms/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

be/blog/templates/cms/post/list.html
{% extends "cms/base.html" %}

{% load cms_tags %}

{% block title %}
My Blog
{% endblock %}

{% block content %}
<h1>
    My Blog
</h1>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "cms:post_list_by_tag" tag.slug %}">
        {{tag.name}}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

be/blog/templates/cms/post/search.html
{% extends "cms/base.html" %}
{% load cms_tags %}

{% block title %}
Search
{% endblock %}

{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}" </h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result {{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{{ post.body|markdown|truncatewords_html:12}}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
{% else %}
<h1>Search for posts</h1>
<form method="GET">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

be/blog/templates/cms/post/share.html
{% extends "cms/base.html" %}

{% block title %}
    Share a post
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail has been sent successfully.</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email.</h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}